# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Michael Neuder
tagline:          'a'
description:      ''
url:              http://micheal.neuder.github.io

author:
  name:           'Michael Neuder'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/michaelneuder/michaelneuder.github.io
