# Permalinks
permalink:        pretty

# Setup
title:            Michael Neuder
tagline:          ''
description:      ''
url:              http://michealneuder.github.io

author:
  name:           'Michael Neuder'

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/michaelneuder/michaelneuder.github.io
